# This file is overwritten by one in alphagov-deployment at deploy time
development:
  clients:
    default:
      hosts:
        - localhost
      database: govuk_content_development
  options:
    use_activesupport_time_zone: true

test:
  clients:
    default:
      hosts:
        - localhost
      # Don't want this interfering with a concurrent Panopticon test run
      database: govuk_content_publisher_test
      options:
        read:
          mode: :primary
        max_pool_size: 1
  options:
    use_activesupport_time_zone: true

# set these environment variables on your prod server
production:
  clients:
    default:
      hosts:
        - <%= ENV['MONGOID_HOST'] %>
      port: <%= ENV['MONGOID_PORT'] %>
      database: <%= ENV['MONGOID_DATABASE'] %>
      options:
        user: <%= ENV['MONGOID_USERNAME'] %>
        password: <%= ENV['MONGOID_PASSWORD'] %>
  options:
    use_activesupport_time_zone: true
